import pandas as pd
from sklearn.preprocessing import StandardScaler

# Load the raw data
data = pd.read_csv('../data/raw/data_preview.csv')

# Handle missing values
data.fillna(method='ffill', inplace=True)

# Standardize the data
scaler = StandardScaler()
data[['Air temperature [K]', 'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]', 'Tool wear [min]']] = scaler.fit_transform(
    data[['Air temperature [K]', 'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]', 'Tool wear [min]']])

# Create lag features for all sensor columns
lag_features = ['Air temperature [K]', 'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]', 'Tool wear [min]']
for lag in range(1, 4):  # Reduced the number of lag features to avoid dropping too many rows
    for feature in lag_features:
        data[f'{feature}_lag_{lag}'] = data[feature].shift(lag)

# Print data before dropping NaN values
print("Data before dropping NaN values:")
print(data.head(20))

# Drop rows with NaN values generated by lag features
data.dropna(inplace=True)

# Ensure the 'Machine failure' column is present after creating lag features
assert 'Machine failure' in data.columns, "'Machine failure' column is missing!"

# Print the shape of the processed data
print(f"Processed data shape: {data.shape}")

# Save the data with lag features
data.to_csv('../data/processed/processed_data_with_lags.csv', index=False)

