database:
  url: postgresql://predictive_maintenance_owner:l2iqhScLz9PQ@ep-floral-meadow-a5zfc3b8.us-east-2.aws.neon.tech/predictive_maintenance?sslmode=require
cmdbuild:
  url: postgresql://cmdbuild:cmdbuild@cmdbuild_db:5432/cmdbuild_r2u2

openmaint:
   url: postgresql://postgres:postgres@localhost:5433/openmaint