database:
  url: postgresql://predictive_maintenance_owner:***************/predictive_maintenance?sslmode=require
cmdbuild:
  url: postgresql://cmdbuild:cmdbuild@cmdbuild_db:5432/cmdbuild_r2u2

openmaint:
   url: postgresql://postgres:postgres@localhost:5433/openmaint
